// JavaScript Document
$('#sp-gold').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})

$('#sp-gold-pro').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})

$('#sp-other').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})